### ISSUE TITLE
Text Edits

### ISSUE THREAD

**Issue by hymm** [hymm/squid-tracks#2]
A bunch of text edits suggested by Selky

## About Page
* [x] rewrite stat.ink setup instructions
* [x] Home Page needs intro
* [x] Auto upload #4 needs grammar corrections
* [x] Need a better term for **Polling** Checking?
* [x] Delete AutoUpload step #3
* [x] Ready to poll Again?
* [x] Note is not obvious move to top of section until problem is corrected
* [x] Change **pull down menu** to **drop down menu**
* [x] Manual upload #2 Name table Table for **Last 50 Battles**

## Results Page
* [x] Change "Results" name to something else.  "Battle History" maybe?
* [x] Add # to Battle #X Details
* [x] Change "Their Team" to "Enemy Team"?
* [x] Add units to elapsed time
* [x] Nickname -> Player
* [x] Results Summary -> Last 50 Battles Summary
* [x] Results -> Last 50 Battles
