### ISSUE TITLE
Roadmap to Version 0.3.0

### ISSUE THREAD

**Issue by hymm** [hymm/squid-tracks#3]
## For 0.3.0
* [x] added anonymizer for people who like to screenshot
* [x] add custom jr `momiji`
* [x] add tracking for unhandled error
* [x] add support for new splatnet fields to stat.ink export #17 
* [x] export last 50 battles to csv #53 
* [x] strikeout player on battle details if there's a dc
* [x] add max values to radar charts
* [x] add support for annie store
* [x] added fest power to battle details
* [x] fixed bug in battle details when players use the same name
* [x] fixed records page displaying sz, tc, and rm ranks the same
* [x] fixed bug with stat.ink uploaded status being assigned to the wrong battle
* [x] added ability to turn on fiddler proxy with environment variable

## For 0.2.4
* [x] removed turf bonus points for ranked games
* [x] add option to switch user language #25
* [x] show level in team tables (more info)
* [x] added radar charts
* [x] added json copy to clipboard
* [x] add power to last 50 battles table
* [x] added translation support to results, records, and schedule
* [x] calculation for per minutes stats was wrong, now fixed
* [x] removed s+ numbers from details, splatnet was not sending the real numbers
* [x] removed bonus from turf inked for ranked games uploaded to stat.ink
* [x] added logging of uncaught errors to help with debugging
* [x] add support for stat.ink fest attributes #17 

## For 0.2.3
* [x] change stat.ink image from image_judge to image_result
* [x] show session token expiration date on settings page
* [x] added iksm tokem for debugging purposes
* [x] show unuploaded battles on last 50 battles table
* [x] change arrows to increment through array instead of battle number #31
* [x] accept stat.ink 302 errors #36 
* [x] memoize or cache getting game details
* [x] option to show stats as a rate on last 50 battles
* [x] add forge pro
* [x] add sloshing machine
* [x] add manta maria
* [x] add highlighting for pure and shiny gear
* [x] move stat.ink upload info into separate file

## For 0.2.2
* [x] add sort order to details table
* [x] add image from splatnet to stat.ink upload #18
* [x] switch to gear used on battle details page
* [x] change details table to display k+a(a) and k - d in the same column
* [x] make spelling of squidTracks consistent #23 
* [x] change weapons text to weapons images on results page
* [x] switch stat.ink uploads to asynchronous calls

## For Public Beta
* [x] fix issues in #2
* [x] Fix cursor on some links, is showing text selection on the ones that don't have an href
* [x] Go back to top when selecting a battle in last 50 battles table
* [x] Switch Battle Details Paging arrows
* [x] Show start time as local time
* [x] Add player ranks to team tables
* [x] Sorting on Tables
* [x] Better feedback on clicking buttons
* [x] only list battle numbers that are listed in results
* [x] Disable stat.ink buttons if session Token is not defined
* [x] add link to stat.ink battle after upload?
* [x] add schedule page
* [x] fix navigation to top of window
* [x] remember window dimensions

**Comment by hymm** [comment]
info from stat.ink battle upload reply
x-api-location: https://stat.ink/api/v2/battle/8231
x-battle-id: 8231
x-user-screen-name: hymm
