### ISSUE TITLE
Version 1 Roadmap

### ISSUE THREAD

**Issue by hymm** [hymm/squid-tracks#4]
This is a list for what I hope to implement for version 1.  Some of them may slip to 1.x version updates.

## Probably won't make version 1.0
* [ ] Figure out hot to get a smaller nintendo oauth login page
* [ ] Use custom graphics for weapon icons
* [ ] Feature parity with splatnet 2
* [x] Save records to local disk for viewing
* [x] Make sure session token is invalidated on getSessionWithSessionToken error
* [ ] look into how to use babel on backend process to make code syntax consistent
* [ ] start autoupload on startup option
* [ ] add check for updates button

## For Final Version 1.0
* [ ] desktop icon
* [ ] add support for stat.ink gender #17  
* [ ] possibly change background of details to stage map
* [ ] split last 50 battles into multiple tables
* [ ] add expected special (inked/special cost) on battle details
* [ ] Prettier autoupdate status page
* [ ] strikeout battles on 50 battles list if there's a dc #43 
* [ ] gear view for last 50 battles
* [ ] backup stat.ink upload status to cloud #52 
* [x] Figure out how to use travis to build for linux and windows

## For 0.3.4
* [x] fix exception reporting (google analytics)
* [ ] clean up login process and show status 
* [ ] clean up behavior when theres no internet connection #12
* [x] auto login and logout with session cookie
* [ ] lift polling logic up to the app level
* [x] finish #81 
* [ ] add intl support for settings page #15
* [ ] add google analytics (see https://github.com/hymm/squid-tracks/projects/2) #13 
* [x] indication on timeline of rule
* [x] handle stat.ink and splatnet errors better

## For 0.3.3
* [x] Figure out how to use travis to build for mac (linux and windows not working)
* [x] fixed bug with radar charts crashing app

## For 0.3.2
* [x] get weapon and stage maps from stat.ink #42 
* [x] fixed annie store
* [x] fixed battle details not showing sometimes
* [x] prettier battle details
* [x] color details with lobby type

## For 0.3.1
* [x] add warnings and info about using cookie login
* [x] alternative login with cookie hijacking
* [x] upload all battles not uploaded.  (means error handling from stat.ink needs to be better)
* [x] trend for last 50 battles
* [x] added start day and combine hero weapons to league data tab
* [x] change all sendSyncs to send (async)

**Comment by hymm** [comment]
add power to last 50 battles table

**Comment by dofine** [comment]
[] Save records to local disk for viewing
This is great because I'm playing with data visualization. Saving my trouble from manually getting the data using python api.

**Comment by hymm** [comment]
closing in favor of using projects
