### ISSUE TITLE
mitm todo list

### ISSUE THREAD

**Issue by hymm** [hymm/squid-tracks#81]
* [x] fix autoupload button
* [ ] use other ports on error
* [ ] ~look into samsung compatibility (certificate might not work on older devices. may need to convert to a dex file)~
* [ ] ~add tracking to find out how long setup is taking~
* [x] fix navigation.  New redirects seems to be causing a problem
* [x] fix error handling to go back to login when cookie expires
* [x] check cookie valid on login
* [x] fix cookie expiration display
* [x] edit instructions
* [x] type up instructions
* [ ] limit cert interception to nintendo
* [x] show ip address
* [x] make webpage to download cert
* [x] move certs and keys to appdata
* [x] translation

**Comment by hymm** [comment]
closing this in favor of indiviual issues #98, #99, and #100
